import {Router,type Request,type Response} from "express";
import TaskCompletion from "../models/TaskCompletion.js";
import Task from "../models/Task.js";
import {authenticate,completeLearningProgress,createAccount,createSession,getCurrentUser,getLearningProgress,learningDashboard,listQueryHistory,logout,publicUser} from "../services/mongoAuth";
const router=Router();
async function requireUser(req:Request,res:Response){const u=await getCurrentUser(req);if(!u){res.status(401).json({success:false,authenticated:false,error:"Authentication required."});return null;}return u;}
router.post("/signup",async(req,res)=>{const name=typeof req.body?.name==="string"?req.body.name.trim():"";const email=typeof req.body?.email==="string"?req.body.email.trim().toLowerCase():"";const password=typeof req.body?.password==="string"?req.body.password:"";if(name.length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8)return res.status(400).json({success:false,error:"Name, valid email and an 8+ character password are required."});try{const user=await createAccount(name,email,password);await createSession(res,user.localUserId);res.status(201).json({success:true,authenticated:true,user:publicUser(user),accountType:"sqlwhale"});}catch(e:any){if(e?.code===11000)return res.status(409).json({success:false,error:"A SQLWhale account with this email already exists."});console.error(e);res.status(500).json({success:false,error:"Unable to create SQLWhale account."});}});
router.post("/login",async(req,res)=>{const email=typeof req.body?.email==="string"?req.body.email.trim().toLowerCase():"";const password=typeof req.body?.password==="string"?req.body.password:"";try{const user=await authenticate(email,password);if(!user)return res.status(401).json({success:false,error:"Invalid SQLWhale email or password."});await createSession(res,user.localUserId);res.json({success:true,authenticated:true,user:publicUser(user),accountType:"sqlwhale"});}catch(e){console.error(e);res.status(500).json({success:false,error:"Unable to login to SQLWhale."});}});
router.get("/me",async(req,res)=>{try{const u=await getCurrentUser(req);if(!u)return res.status(401).json({success:false,authenticated:false});res.json({success:true,authenticated:true,user:publicUser(u),accountType:"sqlwhale"});}catch(e){console.error(e);res.status(500).json({success:false,error:"Unable to check SQLWhale session."});}});
router.get("/query-history",async(req,res)=>{try{const u=await requireUser(req,res);if(!u)return;const n=Number(req.query.limit),limit=Number.isInteger(n)?Math.min(Math.max(n,1),100):50;res.json({success:true,history:await listQueryHistory(u.localUserId,limit)});}catch(e){console.error(e);res.status(500).json({success:false,error:"Unable to load query history."});}});
router.get("/task-completions",async(req,res)=>{try{const u=await requireUser(req,res);if(!u)return;const items=await TaskCompletion.find({localUserId:u.localUserId}).sort({completedAt:-1}).lean().exec();const taskIds=items.map((x:any)=>x.taskId);const tasks=await Task.find({_id:{$in:taskIds}}).lean().exec();const byId=new Map(tasks.map((t:any)=>[String(t._id),t]));res.json({success:true,completions:items.map((x:any)=>{const t=byId.get(String(x.taskId));return{id:String(x.taskId),title:t?.title||"SQL Task",difficulty:t?.difficulty||"Easy",completedAt:x.completedAt};})});}catch(e){console.error(e);res.status(500).json({success:false,error:"Unable to load completed tasks."});}});
router.get("/learning-dashboard",async(req,res)=>{try{const u=await requireUser(req,res);if(!u)return;res.json({success:true,stats:await learningDashboard(u.localUserId)});}catch(e){console.error(e);res.status(500).json({success:false,error:"Unable to load learning dashboard."});}});
router.get("/learning-progress",async(req,res)=>{try{const u=await requireUser(req,res);if(!u)return;res.json({success:true,progress:await getLearningProgress(u.localUserId)});}catch(e){console.error(e);res.status(500).json({success:false,error:"Unable to load learning progress."});}});
router.post("/learning-progress/:sectionId",async(req,res)=>{const sectionId=typeof req.params.sectionId==="string"?req.params.sectionId.trim():"";if(!/^[a-z0-9-]+$/.test(sectionId))return res.status(400).json({success:false,error:"Invalid learning section."});try{const u=await requireUser(req,res);if(!u)return;res.json({success:true,progress:await completeLearningProgress(u.localUserId,sectionId)});}catch(e){console.error(e);res.status(500).json({success:false,error:"Unable to save learning progress."});}});
router.post("/logout",async(req,res)=>{try{await logout(req,res);res.json({success:true});}catch(e){console.error(e);res.status(500).json({success:false,error:"Unable to logout."});}});
export default router;